using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TeamC;
using System.IO;

namespace TeamC
{


    public class ParentPlayerFarCameraController : MonoBehaviour
    {
        
        public GameObject player;
        private Vector3 offset = new Vector3(0, 10, 11.5f);  // Farï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Ìƒvï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Æ‚ÌˆÊ’uï¿½ï¿½ï¿½ï¿½
        [SerializeField] private SugorokuGameDirector sugorokuGameDirector;

        // Start is called before the first frame update
        void Start()
        {

            // ï¿½Qï¿½[ï¿½ï¿½ï¿½Jï¿½nï¿½ï¿½ï¿½_ï¿½ÌƒJï¿½ï¿½ï¿½ï¿½ï¿½Æƒ^ï¿½[ï¿½Qï¿½bï¿½gï¿½Ì‹ï¿½ï¿½ï¿½ï¿½iï¿½Iï¿½tï¿½Zï¿½bï¿½gï¿½jï¿½ï¿½ï¿½æ“¾

        }

        void Update()
        {
            if (sugorokuGameDirector.currentPlayer != null)
            {
                player = sugorokuGameDirector.currentPlayer;
            }
            else if (sugorokuGameDirector.currentPlayer == null)
            {

            }
        }


        /// <summary>
        /// ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÉƒJï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½æ‚¤ï¿½É‚ï¿½ï¿½é‚½ï¿½ß‚ï¿½LateUpdateï¿½É‚ï¿½ï¿½ï¿½B
        /// </summary>
        void LateUpdate()
        {
            // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ÌˆÊ’uï¿½ï¿½ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ÌˆÊ’uï¿½ÉƒIï¿½tï¿½Zï¿½bï¿½gï¿½ğ‘«‚ï¿½ï¿½ï¿½ï¿½êŠï¿½É‚ï¿½ï¿½ï¿½B
            // ï¿½ï¿½ï¿½ÔŠuï¿½ï¿½Û‚ï¿½ï¿½Â‚Âƒvï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½Ì‰ï¿½]ï¿½Éï¿½ï¿½Eï¿½ï¿½ï¿½ï¿½È‚ï¿½
            this.transform.position = player.transform.position + offset;
            this.transform.rotation = Quaternion.Euler(45f, 180f, 0f);

        }
    }
}
